#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "patch.h"

void retail_init(int a, int b);
void classic_init(int a, int b);
void london_init(int a, int b);
void london61_init(int a, int b);

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    if (fdwReason == DLL_PROCESS_ATTACH)
    {
        HMODULE game_exe = GetModuleHandle(NULL);
        
        if (game_exe && memcmp((char*)game_exe + 0x00010000, "\x05\x00\x83\xC4\x04\x8B\x08\xC1\xF9\x07", 10) == 0)
        {
            patch_call((void*)0x00430194, (void*)retail_init);
        } /* GTA retail */
        
        else if (game_exe && memcmp((char*)game_exe + 0x00010000, "\xC7\x05\x10\x1D\x50\x00\x02\x00\x8A\xD8", 10) == 0)
        {
            patch_call((void*)0x004153D8, (void*)classic_init);
        } /* GTA classic */
        
        else if (game_exe && memcmp((char*)game_exe + 0x00010000, "\x0F\xB6\x40\x07\x50\xE8\x8D\x2D\xFF\xFF", 10) == 0)
        {
            patch_call((void*)0x004BF808, (void*)london_init);
        } /* GTA london */
        
        else if (game_exe && memcmp((char*)game_exe + 0x00010000, "\x90\xA4\x00\x00\x00\x66\x89\x90\xD3\x00", 10) == 0)
        {
            patch_call((void*)0x00420227, (void*)london61_init);
        } /* GTA london 61 */
    }
    
    return TRUE;
}

#ifdef MSS32_EXPORTS
#pragma comment(linker, "/export:_SmackBufferString@8=smackw32x._SmackBufferString@8,@1")
#pragma comment(linker, "/export:_SmackBufferOpen@24=smackw32x._SmackBufferOpen@24,@2")
#pragma comment(linker, "/export:_SmackBufferBlit@32=smackw32x._SmackBufferBlit@32,@3")
#pragma comment(linker, "/export:_SmackBufferFocused@4=smackw32x._SmackBufferFocused@4,@4")
#pragma comment(linker, "/export:_SmackBufferNewPalette@12=smackw32x._SmackBufferNewPalette@12,@5")
#pragma comment(linker, "/export:_SmackBufferClose@4=smackw32x._SmackBufferClose@4,@6")
#pragma comment(linker, "/export:_SmackBufferSetPalette@4=smackw32x._SmackBufferSetPalette@4,@7")
#pragma comment(linker, "/export:_SmackBufferClear@8=smackw32x._SmackBufferClear@8,@8")
#pragma comment(linker, "/export:_SmackSetSystemRes@4=smackw32x._SmackSetSystemRes@4,@9")
#pragma comment(linker, "/export:_SmackBufferToBuffer@32=smackw32x._SmackBufferToBuffer@32,@10")
#pragma comment(linker, "/export:_SmackBufferToBufferTrans@36=smackw32x._SmackBufferToBufferTrans@36,@11")
#pragma comment(linker, "/export:_SmackBufferFromScreen@16=smackw32x._SmackBufferFromScreen@16,@12")
#pragma comment(linker, "/export:_SmackBufferCopyPalette@12=smackw32x._SmackBufferCopyPalette@12,@13")
#pragma comment(linker, "/export:_SmackOpen@12=smackw32x._SmackOpen@12,@14")
#pragma comment(linker, "/export:_SmackSimulate@4=smackw32x._SmackSimulate@4,@15")
#pragma comment(linker, "/export:_SmackFrameRate@4=smackw32x._SmackFrameRate@4,@16")
#pragma comment(linker, "/export:_SmackSoundOnOff@8=smackw32x._SmackSoundOnOff@8,@17")
#pragma comment(linker, "/export:_SmackClose@4=smackw32x._SmackClose@4,@18")
#pragma comment(linker, "/export:_SmackDoFrame@4=smackw32x._SmackDoFrame@4,@19")
#pragma comment(linker, "/export:_SmackSummary@8=smackw32x._SmackSummary@8,@20")
#pragma comment(linker, "/export:_SmackNextFrame@4=smackw32x._SmackNextFrame@4,@21")
#pragma comment(linker, "/export:_SmackToScreen@24=smackw32x._SmackToScreen@24,@22")
#pragma comment(linker, "/export:_SmackToBuffer@28=smackw32x._SmackToBuffer@28,@23")
#pragma comment(linker, "/export:_SmackColorTrans@8=smackw32x._SmackColorTrans@8,@24")
#pragma comment(linker, "/export:_SmackColorRemap@16=smackw32x._SmackColorRemap@16,@25")
#pragma comment(linker, "/export:_SmackGetTrackData@12=smackw32x._SmackGetTrackData@12,@26")
#pragma comment(linker, "/export:_SmackGoto@8=smackw32x._SmackGoto@8,@27")
#pragma comment(linker, "/export:_SmackToBufferRect@8=smackw32x._SmackToBufferRect@8,@28")
#pragma comment(linker, "/export:_SmackSoundInTrack@8=smackw32x._SmackSoundInTrack@8,@29")
#pragma comment(linker, "/export:_SmackVolumePan@16=smackw32x._SmackVolumePan@16,@30")
#pragma comment(linker, "/export:_SmackSoundCheck@0=smackw32x._SmackSoundCheck@0,@31")
#pragma comment(linker, "/export:_SmackWait@4=smackw32x._SmackWait@4,@32")
#pragma comment(linker, "/export:_SmackSoundUseMSS@4=smackw32x._SmackSoundUseMSS@4,@33")
#pragma comment(linker, "/export:_SmackSoundUseDW@12=smackw32x._SmackSoundUseDW@12,@34")
#pragma comment(linker, "/export:_donemarker@20=smackw32x._donemarker@20,@35")
#pragma comment(linker, "/export:_TimerFunc@20=smackw32x._TimerFunc@20,@36")
#pragma comment(linker, "/export:_SetDirectSoundHWND@4=smackw32x._SetDirectSoundHWND@4,@37")
#pragma comment(linker, "/export:_SmackSoundUseDirectSound@4=smackw32x._SmackSoundUseDirectSound@4,@38")
#pragma comment(linker, "/export:_SmackSoundUseWin@0=smackw32x._SmackSoundUseWin@0,@39")
#else
#pragma comment(linker, "/export:_AIL_MIDI_handle_reacquire@4=MSS32x._AIL_MIDI_handle_reacquire@4,@1")
#pragma comment(linker, "/export:_AIL_MIDI_handle_release@4=MSS32x._AIL_MIDI_handle_release@4,@2")
#pragma comment(linker, "/export:_AIL_XMIDI_master_volume@4=MSS32x._AIL_XMIDI_master_volume@4,@3")
#pragma comment(linker, "/export:_AIL_active_sample_count@4=MSS32x._AIL_active_sample_count@4,@4")
#pragma comment(linker, "/export:_AIL_active_sequence_count@4=MSS32x._AIL_active_sequence_count@4,@5")
#pragma comment(linker, "/export:_AIL_allocate_file_sample@12=MSS32x._AIL_allocate_file_sample@12,@6")
#pragma comment(linker, "/export:_AIL_allocate_sample_handle@4=MSS32x._AIL_allocate_sample_handle@4,@7")
#pragma comment(linker, "/export:_AIL_allocate_sequence_handle@4=MSS32x._AIL_allocate_sequence_handle@4,@8")
#pragma comment(linker, "/export:_AIL_auto_service_stream@8=MSS32x._AIL_auto_service_stream@8,@9")
#pragma comment(linker, "/export:_AIL_background@0=MSS32x._AIL_background@0,@10")
#pragma comment(linker, "/export:_AIL_branch_index@8=MSS32x._AIL_branch_index@8,@11")
#pragma comment(linker, "/export:_AIL_channel_notes@8=MSS32x._AIL_channel_notes@8,@12")
#pragma comment(linker, "/export:_AIL_close_stream@4=MSS32x._AIL_close_stream@4,@13")
#pragma comment(linker, "/export:_AIL_controller_value@12=MSS32x._AIL_controller_value@12,@14")
#pragma comment(linker, "/export:_AIL_create_wave_synthesizer@16=MSS32x._AIL_create_wave_synthesizer@16,@15")
#pragma comment(linker, "/export:_AIL_delay@4=MSS32x._AIL_delay@4,@16")
#pragma comment(linker, "/export:_AIL_destroy_wave_synthesizer@4=MSS32x._AIL_destroy_wave_synthesizer@4,@17")
#pragma comment(linker, "/export:_AIL_digital_configuration@16=MSS32x._AIL_digital_configuration@16,@18")
#pragma comment(linker, "/export:_AIL_digital_handle_reacquire@4=MSS32x._AIL_digital_handle_reacquire@4,@19")
#pragma comment(linker, "/export:_AIL_digital_handle_release@4=MSS32x._AIL_digital_handle_release@4,@20")
#pragma comment(linker, "/export:_AIL_digital_master_volume@4=MSS32x._AIL_digital_master_volume@4,@21")
#pragma comment(linker, "/export:_AIL_end_sample@4=MSS32x._AIL_end_sample@4,@22")
#pragma comment(linker, "/export:_AIL_end_sequence@4=MSS32x._AIL_end_sequence@4,@23")
#pragma comment(linker, "/export:_AIL_file_error@0=MSS32x._AIL_file_error@0,@24")
#pragma comment(linker, "/export:_AIL_file_read@8=MSS32x._AIL_file_read@8,@25")
#pragma comment(linker, "/export:_AIL_file_size@4=MSS32x._AIL_file_size@4,@26")
#pragma comment(linker, "/export:_AIL_file_write@12=MSS32x._AIL_file_write@12,@27")
#pragma comment(linker, "/export:_AIL_get_DirectSound_info@12=MSS32x._AIL_get_DirectSound_info@12,@28")
#pragma comment(linker, "/export:_AIL_get_preference@4=MSS32x._AIL_get_preference@4,@29")
#pragma comment(linker, "/export:_AIL_init_sample@4=MSS32x._AIL_init_sample@4,@30")
#pragma comment(linker, "/export:_AIL_init_sequence@12=MSS32x._AIL_init_sequence@12,@31")
#pragma comment(linker, "/export:_AIL_last_error@0=MSS32x._AIL_last_error@0,@32")
#pragma comment(linker, "/export:_AIL_load_sample_buffer@16=MSS32x._AIL_load_sample_buffer@16,@33")
#pragma comment(linker, "/export:_AIL_lock@0=MSS32x._AIL_lock@0,@34")
#pragma comment(linker, "/export:_AIL_lock_channel@4=MSS32x._AIL_lock_channel@4,@35")
#pragma comment(linker, "/export:_AIL_map_sequence_channel@12=MSS32x._AIL_map_sequence_channel@12,@36")
#pragma comment(linker, "/export:_AIL_mem_alloc_lock@4=MSS32x._AIL_mem_alloc_lock@4,@37")
#pragma comment(linker, "/export:_AIL_mem_free_lock@4=MSS32x._AIL_mem_free_lock@4,@38")
#pragma comment(linker, "/export:_AIL_midiOutClose@4=MSS32x._AIL_midiOutClose@4,@39")
#pragma comment(linker, "/export:_AIL_midiOutOpen@12=MSS32x._AIL_midiOutOpen@12,@40")
#pragma comment(linker, "/export:_AIL_minimum_sample_buffer_size@12=MSS32x._AIL_minimum_sample_buffer_size@12,@41")
#pragma comment(linker, "/export:_AIL_ms_count@0=MSS32x._AIL_ms_count@0,@42")
#pragma comment(linker, "/export:_AIL_open_stream@12=MSS32x._AIL_open_stream@12,@43")
#pragma comment(linker, "/export:_AIL_pause_stream@8=MSS32x._AIL_pause_stream@8,@44")
#pragma comment(linker, "/export:_AIL_quick_copy@4=MSS32x._AIL_quick_copy@4,@45")
#pragma comment(linker, "/export:_AIL_quick_halt@4=MSS32x._AIL_quick_halt@4,@46")
#pragma comment(linker, "/export:_AIL_quick_handles@8=MSS32x._AIL_quick_handles@8,@47")
#pragma comment(linker, "/export:_AIL_quick_load@4=MSS32x._AIL_quick_load@4,@48")
#pragma comment(linker, "/export:_AIL_quick_load_and_play@12=MSS32x._AIL_quick_load_and_play@12,@49")
#pragma comment(linker, "/export:_AIL_quick_play@8=MSS32x._AIL_quick_play@8,@50")
#pragma comment(linker, "/export:_AIL_quick_set_speed@8=MSS32x._AIL_quick_set_speed@8,@51")
#pragma comment(linker, "/export:_AIL_quick_set_volume@12=MSS32x._AIL_quick_set_volume@12,@52")
#pragma comment(linker, "/export:_AIL_quick_shutdown@0=MSS32x._AIL_quick_shutdown@0,@53")
#pragma comment(linker, "/export:_AIL_quick_startup@20=MSS32x._AIL_quick_startup@20,@54")
#pragma comment(linker, "/export:_AIL_quick_status@4=MSS32x._AIL_quick_status@4,@55")
#pragma comment(linker, "/export:_AIL_quick_unload@4=MSS32x._AIL_quick_unload@4,@56")
#pragma comment(linker, "/export:_AIL_redbook_close@4=MSS32x._AIL_redbook_close@4,@57")
#pragma comment(linker, "/export:_AIL_redbook_eject@4=MSS32x._AIL_redbook_eject@4,@58")
#pragma comment(linker, "/export:_AIL_redbook_id@4=MSS32x._AIL_redbook_id@4,@59")
#pragma comment(linker, "/export:_AIL_redbook_open@4=MSS32x._AIL_redbook_open@4,@60")
#pragma comment(linker, "/export:_AIL_redbook_pause@4=MSS32x._AIL_redbook_pause@4,@61")
#pragma comment(linker, "/export:_AIL_redbook_play@12=MSS32x._AIL_redbook_play@12,@62")
#pragma comment(linker, "/export:_AIL_redbook_position@4=MSS32x._AIL_redbook_position@4,@63")
#pragma comment(linker, "/export:_AIL_redbook_resume@4=MSS32x._AIL_redbook_resume@4,@64")
#pragma comment(linker, "/export:_AIL_redbook_retract@4=MSS32x._AIL_redbook_retract@4,@65")
#pragma comment(linker, "/export:_AIL_redbook_set_volume@8=MSS32x._AIL_redbook_set_volume@8,@66")
#pragma comment(linker, "/export:_AIL_redbook_status@4=MSS32x._AIL_redbook_status@4,@67")
#pragma comment(linker, "/export:_AIL_redbook_stop@4=MSS32x._AIL_redbook_stop@4,@68")
#pragma comment(linker, "/export:_AIL_redbook_track@4=MSS32x._AIL_redbook_track@4,@69")
#pragma comment(linker, "/export:_AIL_redbook_track_info@16=MSS32x._AIL_redbook_track_info@16,@70")
#pragma comment(linker, "/export:_AIL_redbook_tracks@4=MSS32x._AIL_redbook_tracks@4,@71")
#pragma comment(linker, "/export:_AIL_redbook_volume@4=MSS32x._AIL_redbook_volume@4,@72")
#pragma comment(linker, "/export:_AIL_register_EOB_callback@8=MSS32x._AIL_register_EOB_callback@8,@73")
#pragma comment(linker, "/export:_AIL_register_EOF_callback@8=MSS32x._AIL_register_EOF_callback@8,@74")
#pragma comment(linker, "/export:_AIL_register_EOS_callback@8=MSS32x._AIL_register_EOS_callback@8,@75")
#pragma comment(linker, "/export:_AIL_register_ICA_array@8=MSS32x._AIL_register_ICA_array@8,@76")
#pragma comment(linker, "/export:_AIL_register_SOB_callback@8=MSS32x._AIL_register_SOB_callback@8,@77")
#pragma comment(linker, "/export:_AIL_register_beat_callback@8=MSS32x._AIL_register_beat_callback@8,@78")
#pragma comment(linker, "/export:_AIL_register_event_callback@8=MSS32x._AIL_register_event_callback@8,@79")
#pragma comment(linker, "/export:_AIL_register_prefix_callback@8=MSS32x._AIL_register_prefix_callback@8,@80")
#pragma comment(linker, "/export:_AIL_register_sequence_callback@8=MSS32x._AIL_register_sequence_callback@8,@81")
#pragma comment(linker, "/export:_AIL_register_stream_callback@8=MSS32x._AIL_register_stream_callback@8,@82")
#pragma comment(linker, "/export:_AIL_register_timbre_callback@8=MSS32x._AIL_register_timbre_callback@8,@83")
#pragma comment(linker, "/export:_AIL_register_timer@4=MSS32x._AIL_register_timer@4,@84")
#pragma comment(linker, "/export:_AIL_register_trigger_callback@8=MSS32x._AIL_register_trigger_callback@8,@85")
#pragma comment(linker, "/export:_AIL_release_all_timers@0=MSS32x._AIL_release_all_timers@0,@86")
#pragma comment(linker, "/export:_AIL_release_channel@8=MSS32x._AIL_release_channel@8,@87")
#pragma comment(linker, "/export:_AIL_release_sample_handle@4=MSS32x._AIL_release_sample_handle@4,@88")
#pragma comment(linker, "/export:_AIL_release_sequence_handle@4=MSS32x._AIL_release_sequence_handle@4,@89")
#pragma comment(linker, "/export:_AIL_release_timer_handle@4=MSS32x._AIL_release_timer_handle@4,@90")
#pragma comment(linker, "/export:_AIL_resume_sample@4=MSS32x._AIL_resume_sample@4,@91")
#pragma comment(linker, "/export:_AIL_resume_sequence@4=MSS32x._AIL_resume_sequence@4,@92")
#pragma comment(linker, "/export:_AIL_sample_buffer_info@20=MSS32x._AIL_sample_buffer_info@20,@93")
#pragma comment(linker, "/export:_AIL_sample_buffer_ready@4=MSS32x._AIL_sample_buffer_ready@4,@94")
#pragma comment(linker, "/export:_AIL_sample_loop_count@4=MSS32x._AIL_sample_loop_count@4,@95")
#pragma comment(linker, "/export:_AIL_sample_pan@4=MSS32x._AIL_sample_pan@4,@96")
#pragma comment(linker, "/export:_AIL_sample_playback_rate@4=MSS32x._AIL_sample_playback_rate@4,@97")
#pragma comment(linker, "/export:_AIL_sample_position@4=MSS32x._AIL_sample_position@4,@98")
#pragma comment(linker, "/export:_AIL_sample_status@4=MSS32x._AIL_sample_status@4,@99")
#pragma comment(linker, "/export:_AIL_sample_user_data@8=MSS32x._AIL_sample_user_data@8,@100")
#pragma comment(linker, "/export:_AIL_sample_volume@4=MSS32x._AIL_sample_volume@4,@101")
#pragma comment(linker, "/export:_AIL_send_channel_voice_message@20=MSS32x._AIL_send_channel_voice_message@20,@102")
#pragma comment(linker, "/export:_AIL_send_sysex_message@8=MSS32x._AIL_send_sysex_message@8,@103")
#pragma comment(linker, "/export:_AIL_sequence_loop_count@4=MSS32x._AIL_sequence_loop_count@4,@104")
#pragma comment(linker, "/export:_AIL_sequence_position@12=MSS32x._AIL_sequence_position@12,@105")
#pragma comment(linker, "/export:_AIL_sequence_status@4=MSS32x._AIL_sequence_status@4,@106")
#pragma comment(linker, "/export:_AIL_sequence_tempo@4=MSS32x._AIL_sequence_tempo@4,@107")
#pragma comment(linker, "/export:_AIL_sequence_user_data@8=MSS32x._AIL_sequence_user_data@8,@108")
#pragma comment(linker, "/export:_AIL_sequence_volume@4=MSS32x._AIL_sequence_volume@4,@109")
#pragma comment(linker, "/export:_AIL_serve@0=MSS32x._AIL_serve@0,@110")
#pragma comment(linker, "/export:_AIL_service_stream@8=MSS32x._AIL_service_stream@8,@111")
#pragma comment(linker, "/export:_AIL_set_XMIDI_master_volume@8=MSS32x._AIL_set_XMIDI_master_volume@8,@112")
#pragma comment(linker, "/export:_AIL_set_digital_master_volume@8=MSS32x._AIL_set_digital_master_volume@8,@113")
#pragma comment(linker, "/export:_AIL_set_direct_buffer_control@8=MSS32x._AIL_set_direct_buffer_control@8,@114")
#pragma comment(linker, "/export:_AIL_set_error@4=MSS32x._AIL_set_error@4,@115")
#pragma comment(linker, "/export:_AIL_set_preference@8=MSS32x._AIL_set_preference@8,@116")
#pragma comment(linker, "/export:_AIL_set_sample_address@12=MSS32x._AIL_set_sample_address@12,@117")
#pragma comment(linker, "/export:_AIL_set_sample_file@12=MSS32x._AIL_set_sample_file@12,@118")
#pragma comment(linker, "/export:_AIL_set_sample_loop_block@12=MSS32x._AIL_set_sample_loop_block@12,@119")
#pragma comment(linker, "/export:_AIL_set_sample_loop_count@8=MSS32x._AIL_set_sample_loop_count@8,@120")
#pragma comment(linker, "/export:_AIL_set_sample_pan@8=MSS32x._AIL_set_sample_pan@8,@121")
#pragma comment(linker, "/export:_AIL_set_sample_playback_rate@8=MSS32x._AIL_set_sample_playback_rate@8,@122")
#pragma comment(linker, "/export:_AIL_set_sample_position@8=MSS32x._AIL_set_sample_position@8,@123")
#pragma comment(linker, "/export:_AIL_set_sample_type@12=MSS32x._AIL_set_sample_type@12,@124")
#pragma comment(linker, "/export:_AIL_set_sample_user_data@12=MSS32x._AIL_set_sample_user_data@12,@125")
#pragma comment(linker, "/export:_AIL_set_sample_volume@8=MSS32x._AIL_set_sample_volume@8,@126")
#pragma comment(linker, "/export:_AIL_set_sequence_loop_count@8=MSS32x._AIL_set_sequence_loop_count@8,@127")
#pragma comment(linker, "/export:_AIL_set_sequence_tempo@12=MSS32x._AIL_set_sequence_tempo@12,@128")
#pragma comment(linker, "/export:_AIL_set_sequence_user_data@12=MSS32x._AIL_set_sequence_user_data@12,@129")
#pragma comment(linker, "/export:_AIL_set_sequence_volume@12=MSS32x._AIL_set_sequence_volume@12,@130")
#pragma comment(linker, "/export:_AIL_set_stream_loop_count@8=MSS32x._AIL_set_stream_loop_count@8,@131")
#pragma comment(linker, "/export:_AIL_set_stream_pan@8=MSS32x._AIL_set_stream_pan@8,@132")
#pragma comment(linker, "/export:_AIL_set_stream_playback_rate@8=MSS32x._AIL_set_stream_playback_rate@8,@133")
#pragma comment(linker, "/export:_AIL_set_stream_position@8=MSS32x._AIL_set_stream_position@8,@134")
#pragma comment(linker, "/export:_AIL_set_stream_user_data@12=MSS32x._AIL_set_stream_user_data@12,@135")
#pragma comment(linker, "/export:_AIL_set_stream_volume@8=MSS32x._AIL_set_stream_volume@8,@136")
#pragma comment(linker, "/export:_AIL_set_timer_divisor@8=MSS32x._AIL_set_timer_divisor@8,@137")
#pragma comment(linker, "/export:_AIL_set_timer_frequency@8=MSS32x._AIL_set_timer_frequency@8,@138")
#pragma comment(linker, "/export:_AIL_set_timer_period@8=MSS32x._AIL_set_timer_period@8,@139")
#pragma comment(linker, "/export:_AIL_set_timer_user@8=MSS32x._AIL_set_timer_user@8,@140")
#pragma comment(linker, "/export:_AIL_shutdown@0=MSS32x._AIL_shutdown@0,@141")
#pragma comment(linker, "/export:_AIL_start_all_timers@0=MSS32x._AIL_start_all_timers@0,@142")
#pragma comment(linker, "/export:_AIL_start_sample@4=MSS32x._AIL_start_sample@4,@143")
#pragma comment(linker, "/export:_AIL_start_sequence@4=MSS32x._AIL_start_sequence@4,@144")
#pragma comment(linker, "/export:_AIL_start_stream@4=MSS32x._AIL_start_stream@4,@145")
#pragma comment(linker, "/export:_AIL_start_timer@4=MSS32x._AIL_start_timer@4,@146")
#pragma comment(linker, "/export:_AIL_startup@0=MSS32x._AIL_startup@0,@147")
#pragma comment(linker, "/export:_AIL_stop_all_timers@0=MSS32x._AIL_stop_all_timers@0,@148")
#pragma comment(linker, "/export:_AIL_stop_sample@4=MSS32x._AIL_stop_sample@4,@149")
#pragma comment(linker, "/export:_AIL_stop_sequence@4=MSS32x._AIL_stop_sequence@4,@150")
#pragma comment(linker, "/export:_AIL_stop_timer@4=MSS32x._AIL_stop_timer@4,@151")
#pragma comment(linker, "/export:_AIL_stream_info@20=MSS32x._AIL_stream_info@20,@152")
#pragma comment(linker, "/export:_AIL_stream_loop_count@4=MSS32x._AIL_stream_loop_count@4,@153")
#pragma comment(linker, "/export:_AIL_stream_pan@4=MSS32x._AIL_stream_pan@4,@154")
#pragma comment(linker, "/export:_AIL_stream_playback_rate@4=MSS32x._AIL_stream_playback_rate@4,@155")
#pragma comment(linker, "/export:_AIL_stream_position@4=MSS32x._AIL_stream_position@4,@156")
#pragma comment(linker, "/export:_AIL_stream_status@4=MSS32x._AIL_stream_status@4,@157")
#pragma comment(linker, "/export:_AIL_stream_user_data@8=MSS32x._AIL_stream_user_data@8,@158")
#pragma comment(linker, "/export:_AIL_stream_volume@4=MSS32x._AIL_stream_volume@4,@159")
#pragma comment(linker, "/export:_AIL_true_sequence_channel@8=MSS32x._AIL_true_sequence_channel@8,@160")
#pragma comment(linker, "/export:_AIL_unlock@0=MSS32x._AIL_unlock@0,@161")
#pragma comment(linker, "/export:_AIL_waveOutClose@4=MSS32x._AIL_waveOutClose@4,@162")
#pragma comment(linker, "/export:_AIL_waveOutOpen@16=MSS32x._AIL_waveOutOpen@16,@163")
#pragma comment(linker, "/export:_DllMain@12=MSS32x._DllMain@12,@164")
#endif
